### ISSUE TITLE
Twitch theme setting does not persist

### ISSUE THREAD

**Issue by gonzalezjo** [scs-ben/tcec-gui#176]
If you set Twitch Theme to dark and refresh the page, it will go back into light mode.

**Comment by scs-ben** [comment]
this has been fixed

**Comment by tcecspectator** [comment]
This is not completely fixed.  If you set your TCEC to dark (moon) and twitch theme to light and then refresh the page, the twitch theme refreshes to dark.
